[params]
  paginate = 5
  copyrightYears = "MMXXI - MMXXV"
  minimalUI = true
  disableScale = true
  description = "Experimental blogs"
  debug = false

  [params.preview]
    outputPrefix = "ogPreview-overlay"
    outputSuffix = ".png"
    format =  "svg"
    image = "front.png"
    source = "overlay"
    [params.preview.size]
      height = 630
      width = 1200
    [params.preview.svg]
      template = "./Source Files/Other/preview-template.svg"
      scale = "width"
      removeMissing = true

  [params.footer]
      privacy = true

  [params.robots]
    llmsTXT = true
