[[headers]]
  for = "/**"
  [headers.values]
    Upgrade-Insecure-Requests = "0"
    X-Projektemacher = "true"
    Content-Security-Policy =  "default-src 'self' data: ws://127.0.0.1:* ws://localhost:* http://127.0.0.1:* http://localhost:*; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://127.0.0.1:* http://localhost:*; connect-src https://dpdb.webvr.rocks https://static.projektemacher.org ws://localhost:* http://127.0.0.1:* http://localhost:*;"
    Referrer-Policy = 'strict-origin-when-cross-origin'
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"
    Connection = "keep-alive"
    Keep-Alive = "timeout=5"
