name: github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 23 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Python devDependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow termcolor

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'
          extended: true

      - name: Create IIIF derivates
# UID is als available via $(id -u)
        run: |
          echo "Running as ${UID}"
          docker run -e CHOWN_UID=${UID} -e URL_PREFIX="https://labs.projektemacher.org/" -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest-jxl sh -c "cd ${PWD} && ./scripts/iiif.sh && ./scripts/iiif-jxl.sh"
#          docker run -e CHOWN_UID=${UID} -e URL_PREFIX="https://labs.projektemacher.org/" -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest-jxl sh -c "cd ${PWD} && ./scripts/iiif-jxl.sh"

      - name: Generate Files
        env:
          SKIP_IIIF: yes
        run: |
          sudo apt-get install bash jq findutils
          ./scripts/setup.sh

      - name: Build Hugo site
        run: hugo --i18n-warnings

      - name: Validate JSON
        run: |
          yarn run validate

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
