name: Check Projketemacher Static SSL Certificate

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Certificate
        run: |
          if true | openssl s_client -connect static.projektemacher.org:443 2>/dev/null | \
            openssl x509 -noout -checkend 0; then
            echo "Certificate is not expired"
            exit 0
          else
            echo "Certificate is expired"
            exit 1
          fi
